openapi: "3.0.2"
info:
  title: Resto Management
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /ingredient:
    get:
      responses:
        '200':
          description: OK
